package com.neuedu.pojo;

import java.util.Date;
import java.util.Objects;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.cstatus
     *
     * @mbg.generated
     */
    private Integer cstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_category.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.id
     *
     * @return the value of neuedu_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.id
     *
     * @param id the value for neuedu_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.parent_id
     *
     * @return the value of neuedu_category.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.parent_id
     *
     * @param parentId the value for neuedu_category.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.cname
     *
     * @return the value of neuedu_category.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.cname
     *
     * @param cname the value for neuedu_category.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.cstatus
     *
     * @return the value of neuedu_category.cstatus
     *
     * @mbg.generated
     */
    public Integer getCstatus() {
        return cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.cstatus
     *
     * @param cstatus the value for neuedu_category.cstatus
     *
     * @mbg.generated
     */
    public void setCstatus(Integer cstatus) {
        this.cstatus = cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.create_time
     *
     * @return the value of neuedu_category.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.create_time
     *
     * @param createTime the value for neuedu_category.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column neuedu_category.update_time
     *
     * @return the value of neuedu_category.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column neuedu_category.update_time
     *
     * @param updateTime the value for neuedu_category.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    //重写hashcold和equals方法 通过id判断是否相等


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        return Objects.equals(id, category.id);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id);
    }
}