package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);
    Cart selectCartByUserIdAndProductId(@Param("userId") Integer userId,
                                        @Param("productId") Integer productId);
/**
 * 查询用户购物车信息
 * **/
   List<Cart>  selectCartByUserId(Integer userId);

   /**
    * 统计用户购物信息是否全选
    * return >0 说明未全选
    * 统计没有选中商品的数量
    * */
   int isCheckedAll(Integer  userId);

   /**
    * 删除购物车的某些商品
    * **/
   int deleteByUserIdAndProductIds(@Param("userId") Integer userId,
                                   @Param("productIdList") List<Integer> productIdList);

   /**
    *操作购物车商品是否选中
    * 1选中0 未选中
    * 单选全选productId
    * 全选的话：productId可以不用传
    * **/
   int selectOrUselectProduct(@Param("userId") Integer userId,
                              @Param("productId") Integer productId,
                              @Param("check") Integer check);
    /**
     * 购物车中产品的数量
     * **/
    int get_cart_product_count(Integer userId);

    /**
     * 查询购物车中用户已选的商品
     * ***/
    List<Cart> findCartListByUserIdAndChecked(Integer userId);
    /**
     *批量删除
     * **/
    int batchDelete(List<Cart> cartList);
}